apiVersion: metrics.appscode.com/v1alpha1
kind: MetricsConfiguration
metadata:
  name: repository-metrics-config
spec:
  targetRef:
    apiVersion: stash.appscode.com/v1alpha1
    kind: Repository
  metrics:
    - name: stash_repository_created
      help: "Unix creation timestamp of this Repository"
      type: gauge
      field:
        path: .metadata.creationTimestamp
        type: DateTime
      metricValue:
        valueFromPath: .metadata.creationTimestamp
